// <auto-generated />
namespace Login.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class JimChatV1Code : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JimChatV1Code));
        
        string IMigrationMetadata.Id
        {
            get { return "202007261257237_JimChatV1Code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
